name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      nfsd:
        image: ghcr.io/pborzenkov/nfs-rs:test-daemon
        ports:
          - 11111:2049/tcp
          - 11111:2049/udp
    env:
      TEST_NFS_SERVER: "nfs://127.0.0.1:11111/share?mountport=11111&version=3"
      CARGO_HOME: "~/.nix-cargo"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v11
        with:
          name: pborzenkov
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      # Can't run via 'nix flake check' as the tests do network requests
      - name: Test
        run: |
          nix develop -c cargo fmt --check
          nix develop -c cargo clippy -- --deny warnings
          nix develop -c cargo test
          nix develop -c cargo build
